version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    ignore:
      # don't update until https://github.com/cilium/pwru/issues/8 is resolved.
      - dependency-name: "github.com/cilium/ebpf"
    labels:
    - kind/enhancement

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    rebase-strategy: disabled
    labels:
    - kind/enhancement
